@startuml 
partition "t05_switch" {
  group "sequence05"
    :A;
    switch ( test )
    case ( one )
      :B;
      :C;
    case ( two )
      :D;
      :E;
    case ( three )
      :F;
      :G;
    endswitch
    :H;
  end group
}
@enduml
