@startuml 
partition "t06_mixed" {
  group "sequence06"
    :A;
    if ( XOR ) then ( normal )
      fork
        :B;
      fork again
        :C;
      end fork
      :D;
    else
      :E;
    endif
    :F;
  end group
}
@enduml
