@startuml 
partition "t07_mixed2" {
  group "sequence07"
    :A;
    fork
      switch ( XOR )
      case ( one )
        :B;
      case ( other )
        :C;
      endswitch
    fork again
      :D;
    end fork
    :E;
  end group
}
@enduml
