= plus2json Unhappy Topologies

xtUML Project Analysis Note

== 1 Abstract

This note documents enhancements to 'plus2json' to support more unhappy
path event topologies and scenarios for the --play option.

== 2 Introduction and Background

=== 2.1 Current Behaviour

In the present (Aug 2023) 'plus2json', the following behaviour is
implemented for playing jobs with unhappy events and critical events
defined.

Each time a happy path event tagged as critical is encountered a coin is
tossed.  If the coin is heads, the critical happy path event is played
normally.  If the coin is tails, an unhappy event is substituted in place
of the happy path critical event.  It is linked into the event stream so
that the previous and next events are the same as would have been seen on
the critical event.

When an unhappy event is substituted, it is chosen from the pool of
existing unhappy events with 'select/find any'.  This may or may not be
random but is unconstrained and does differ from run to run.

The above behaviour is repeated for each happy path critical event
encountered.  Therefore, in the presence of multiple happy path critical
events, various combinations of output are possible.  `plus2json --play`
must be run multiple times to observe the various combinations of audit
event instance output.  The output is non-deterministic.

== 3 Requirements

=== 3.1 More Topologies

More and various topologies for the appearance of unhappy events shall be
defined, documented and implemented.

=== 3.2 Command Line Control

A means of controlling the behaviour of '--play' and/or '--play --all'
shall be supplied.

== 4 Analysis

=== 4.1 Proposed Topologies

The following topological strategies are proposed for the substitution and
injection of unhappy events within the runtime audit event instance
streams.

==== 4.1.1 Critical Event Substitution

This is the current behaviour as described above.  It has merit to test
expected but unhappy behaviour.

Alarm conditions __are not__ produced.

==== 4.1.2 Non-Critical Substitution

This strategy replaces a non-critical happy path event with an unhappy
path event and links it identically to the happy path event replaced.
In '--play' mode, the non-critical happy path event is chosen randomly.
In '--play --all' mode, all non-critical happy path events are substituted
one-at-a-time to test the appearance of an unhappy event received in the
topology in place of each non-critical happy path event.

Alarm conditions _are_ produced in _some_ scenarios.

==== 4.1.3 Unhappy Event Insertion Before Critical

This strategy inserts and links an unhappy event into the tine directly
ahead of a critical event.

Alarm conditions _are_ produced in _all_ scenarios.

==== 4.1.4 Unhappy Event Insertion Anywhere

This strategy inserts an unhappy event into the flow anywhere.

Alarm conditions _are_ produced in _some_ scenarios.

==== 4.1.5 Critical Sibling Insertion

This strategy adds an unhappy event as a sibling to a critical event.  In
other words, when a critical event is encountered it is produced and linked
normally.  However, an additional unhappy event is linked to the same
previous event as the critical event.  This produces a (direct) common
ancestor shared by the critical event and the unhappy event.

Alarm conditions _are_ produced in _all_ scenarios.

==== 4.1.6 Unlinked Unhappy Event Production

This strategy produces an unlinked unhappy path event (lost lamb).  The
unhappy event will carry no previous event identifiers.

Alarm conditions _are_ produced in _all_ scenarios.

=== 3.2 Command Line Control

The first thought for command line control is to enable targeted control
of the insert and replace strategies.  Two new modifiers of the '--play'
option could be '--replace' and '--insert'.  Each of these could take an
argument which identified an audit event definition.  For '--replace ABC',
the named audit event definition would define the place where the happy
path event was substituted for an unhappy event.  In this case, 'ABC'
would be replaced with an unhappy path event.  For '--insert XYZ', the
named audit event definition would be used to control where an unhappy
event got inserted (before).  In this case, an unhappy event would be
inserted ahead of 'XYZ'.

'--replace' and '--insert' could have default behaviour.  If no audit
event is named with the option, then the job definition (assumed to be a
job definition used for testing) would be searched for a default named
audit event indicating where the replacement or insertion was to take
place.  For '--replace', 'REPLACEME' could be the target to be replaced
with an unhappy event.  For '--insert', 'INSERTBEFOREME' could be the
target where an unhappy event would inserted.

== 5 Work Required

=== 5.1 Topology Implementation

==== 5.1.1 Critical Event Substitution

This is complete.  More work would be required to support '--all'.

==== 5.1.2 Non-Critical Substitution
==== 5.1.3 Unhappy Event Insertion Before Critical
==== 5.1.4 Unhappy Event Insertion Anywhere
==== 5.1.5 Critical Sibling Insertion
==== 5.1.6 Unlinked Unhappy Event Production

=== 5.2 Command Line Control

* '--replace [event name]' replaces the named event with an unhappy event
* '--replace' (no named event) replaces all events with name 'REPLACEME'
  with an unhappy event
* '--insert [event name]' inserts an unhappy event before the named event
* '--replace' (no named event) inserts an unhappy event before all events
  with name 'INSERTBEFOREME'

== 6 Acceptance Test

. `regression.sh` must continue to pass.
. `run_benchmark.sh` must continue to function.
. Test using the PVprime job definition.

== 7 Document References

. [[dr-1]] https://onefact.atlassian.net/browse/MUN2-117[MUN2-117 plus2json updates for unhappy paths]

---

This work is licensed under the Creative Commons CC0 License

---
