name: Test
on:

  # run on PRs to main
  pull_request:
    branches: [ git_actions_test ]

  # run on push to main
  push:
    branches: [ git_actions_test ]

  # run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: generate parser
        run: |
          antlr4 -Dlanguage=Python3 plus2json/plus2json.g4
      - name: run tests
        run: |
          cd plus2json
          python -m unittest discover

